### ISSUE TITLE
No module named exceptions 

### ISSUE THREAD

**Issue by lukas-stelzl** [MDAnalysis/RotamerConvolveMD#29]
I have tried to used RotamerConvolveMD after installing MDAnalysis from conda. 

 2023  conda config --add channels conda-forge
 2024  conda install mdanalysis 
 2025  pip install --user  RotamerConvolveMD
```
lustelzl@tbsl025:~/Projects/Lisa_BioFF/pre-test$ convolve-mtss-rotamers.py 
Traceback (most recent call last):
  File "/home/tb/lustelzl/.local/bin/convolve-mtss-rotamers.py", line 4, in <module>
    __import__('pkg_resources').run_script('RotamerConvolveMD==1.3.0.dev0', 'convolve-mtss-rotamers.py')
  File "/home/tb/lustelzl/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/tb/lustelzl/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/home/tb/lustelzl/.local/lib/python2.7/site-packages/RotamerConvolveMD-1.3.0.dev0-py2.7.egg/EGG-INFO/scripts/convolve-mtss-rotamers.py", line 26, in <module>
    
  File "/home/tb/lustelzl/.local/lib/python2.7/site-packages/MDAnalysis-0.17.0-py2.7-linux-x86_64.egg/MDAnalysis/__init__.py", line 176, in <module>
    
ImportError: No module named exceptions
lustelzl@tbsl025:~/Projects/Lisa_BioFF/pre-test$ 
```
I will try to figure what is wrong.

**Comment by orbeckst** [comment]
You did not install into your conda environment (`/home/tb/lustelzl/.local/lib/python2.7/site-packages` looks like `pip install --user` – don't use `--user` with conda). In general, mixing this with conda tends to give weird interactions. 

If you insist on having `~/.local` around, I'd create conda environments and use those; you can pip-install into them without problems:
```bash
conda create -n mda3 python=3.6 mdanalysis pandas ...
```
and
```bash
source activate mda3

pip install  RotamerConvolveMD
```
