### ISSUE TITLE
useNOelectron required for convolve-mtss-rotamers.py

### ISSUE THREAD

**Issue by yfichou** [MDAnalysis/RotamerConvolveMD#31]
Hello,
I'm running rotamerConvolveMD 1.3.0 with Window.

I got the following error when trying to run convolve-mtss-rotamers.py. The script run fine if the --useNoelectron option is added though.

Yann

>convolve-mtss-rotamers.py --resid 161 183 --histogramBins 0 80 1 --clashDistance 2.2 --output "testOutput" --plotname "plotname.pdf" --outputRawDistances "dataOut" --dcdfilename "testDCD" --dcdfilenameNoClashes "testDCD_noClash" 5o3l-o-t_resnr.pdb
MDAnalysis  : INFO     MDAnalysis 0.19.2 STARTED logging to 'MDAnalysis.log'
MDAnalysis.app: INFO     Rotamer Convolve MD, release 1.3.0 --- Copyright (c) Philip W Fowler, Oliver Beckstein, Katrin Reichel, and AUTHORS 2011-2017
MDAnalysis.app: INFO     Released under the GNU Public Licence, version 2 (or higher)
MDAnalysis.app: INFO     Please cite: LS Stelzl, PW Fowler, MSP Sansom, O Beckstein. J Mol Biol 426 (2014), 735-751, doi:10.1016/j.jmb.2013.10.024
MDAnalysis.app: INFO     Loading trajectory data as Universe(5o3l-o-t_resnr.pdb)
MDAnalysis.app: INFO     Using rotamer library 'MTSSL 298K 2015' by Gunnar Jeschke
MDAnalysis.app: INFO     Please cite: Polyhach Y, Bordignon E, Jeschke G. Phys Chem Chem Phys. 2011; 13(6):2356-2366. doi: 10.1039/c0cp01865a
MDAnalysis.app: INFO     Starting rotamer distance analysis of trajectory 5o3l-o-t_resnr.pdb...
MDAnalysis.app: INFO     clashDistance = 2.2 A; rotamer library = 'MTSSL 298K 2015'
Step     3/3 [100.0%]
Traceback (most recent call last):
  File "C:\Users\Yann\Anaconda3\Scripts\convolve-mtss-rotamers.py", line 107, in <module>
    useNOelectron=options.useNOelectron)
  File "C:\Users\Yann\Anaconda3\lib\site-packages\rotcon\convolve.py", line 194, in __init__
    distances.append(distance)
UnboundLocalError: local variable 'distance' referenced before assignment

**Comment by orbeckst** [comment]
@katrinr any idea? – I think that might have happened when `--useNOelectron` was introduced.

**Comment by katrinr** [comment]
Thanks for using RotamerConvolveMD. Did you run the tests (e.g. https://github.com/MDAnalysis/RotamerConvolveMD/blob/master/tests/mtssl_2015/test_mtssl_2015.sh) and did it go smoothly?
Are you using MTSL and what is the name of the atom (O1 in the pdb or sth. else)?

**Comment by orbeckst** [comment]
The tests all use --useNOelectron. I don't think we have tests without it with the alternative option. 

--
Oliver Beckstein
email: orbeckst@gmail.com
